spring:
  application:
    name: projections

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/projections}
    username: ${DB_USERNAME:projections}
    password: ${DB_PASSWORD:projections}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    liquibase: INFO
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
        orm:
          jpa: INFO
